---
title: "New Lab"

nodes:
  - label: ios1
    node_definition: iosvl2
    x: 50
    y: 100
    configuration: |
      hostname ios1
      !
  - label: ubuntu1
    node_definition: ubuntu
    x: 200
    y: 100
    configuration: ""
    user_data: |
      #cloud-config
      hostname: ubuntu1
      manage_etc_hosts: true
      users:
        - name: david
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/bash
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEMmKqolX+KhHrl9F//UmXQqEfB+ZL8NkA0biAsQm2w5 davidingwersen52@gmail.com

links:
  - endpoints: [ios1/0, ubuntu1/0]
